@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Sep 07 16:39:20 -0400 2021
REM SW Build 3247384 on Thu Jun 10 19:36:33 MDT 2021
REM
REM IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim CounterMod7Enable_test_behav -key {Behavioral:sim_3:Functional:CounterMod7Enable_test} -tclbatch CounterMod7Enable_test.tcl -view C:/Users/samum/Comp541/Lab3a/CounterMod7Enable_test_behav.wcfg -log simulate.log"
call xsim  CounterMod7Enable_test_behav -key {Behavioral:sim_3:Functional:CounterMod7Enable_test} -tclbatch CounterMod7Enable_test.tcl -view C:/Users/samum/Comp541/Lab3a/CounterMod7Enable_test_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
